import { describe, expect, it } from "vitest";
import { FORBID_ALL_IMPORTS, allowOnly, findImpurities, readModuleSource } from "@/lib/test-utils/purity";

// WHY A TYPES FILE HAS A TEST AT ALL
//
// `purity.test.ts` globs `src/lib/parser/` and asserts every module in it is pure.
// That guarantee is only as strong as what those modules are allowed to IMPORT, and
// #62 put `@/lib/types` on the allowlist so `dictionary.ts` could be typed against
// `DictionaryEntry`. That made `types.ts` the first allowlisted module living
// OUTSIDE the globbed directory — so nothing checked it, and the parser's purity
// claim quietly became conditional on a file no test looked at.
//
// The hole was real, not theoretical: appending `export const LEAK = Date.now();`
// to `types.ts` left the whole parser purity suite green at 6/6. The plan states
// the criterion as "no parser file imports supabaseAdmin, calls fetch, or calls
// new Date() — verified by test, not by inspection", and a guard that stops at the
// directory boundary does not verify that, it verifies one hop of it.
//
// WHY THIS RATHER THAN A TRANSITIVE GUARD. Following imports would mean resolving
// specifiers to files and walking the graph — a `Program` per module and real
// module resolution, which is the weight #75 deliberately did not take on. The
// import graph here is two files deep and both ends are asserted below, so the
// cheap version is complete for the shape the code actually has. If the parser
// allowlist ever grows a third outward edge, this is the file that has to grow with
// it — stated so the next person adding one knows the obligation exists.

describe("types.ts purity", () => {
  // Both permitted imports are type-only, so nothing survives into the emitted JS.
  //
  //   `@/lib/database.types`  allowlisted rather than forbidden because the row types
  //                           are DERIVED from the generated schema on purpose (#48)
  //                           — that import is the mechanism that makes a migration
  //                           break every stale usage, and forbidding it would push
  //                           the app back to hand-written interfaces that silently
  //                           disagree with the schema.
  //
  //   `@/lib/parser/time`     added by #67. `ParseResult` holds `ExtractedTime` whole
  //                           rather than splitting it into `startsAt`/`endsAt`/`kind`,
  //                           which would spell three impossible states.
  //
  //                           ⚠ THIS IS THE ONLY EDGE HERE THAT POINTS OUTWARD, and
  //                           it does NOT incur the obligation the header describes.
  //                           That obligation is about `parser/purity.test.ts`
  //                           allowlisting a module outside its glob — a claim that
  //                           stops at an unasserted file. This edge points INTO the
  //                           parser directory, which that glob already covers in
  //                           full, so the far end is asserted by the suite that
  //                           depends on it. Verified, not assumed: appending
  //                           `Date.now()` to `time.ts` fails
  //                           `parser/purity.test.ts`, not this file.
  //
  //                           It does mean `types.ts` and the parser now import each
  //                           other at the TYPE level (`location.ts` reads
  //                           `LocationMatch` from here). There is no runtime cycle —
  //                           both directions are `import type`, and `time.ts` imports
  //                           nothing from `types.ts` — and the assertion below is
  //                           what keeps the emitted JS empty rather than trusting
  //                           that it stays that way.
  it("imports only erased types, and never touches the network or clock", () => {
    const violations = findImpurities(
      readModuleSource(new URL("./types.ts", import.meta.url).href),
      allowOnly(["@/lib/database.types", "@/lib/parser/time"]),
    );

    expect(violations).toEqual([]);
  });
});

describe("database.types.ts purity", () => {
  // The far end of the chain, and the reason this suite is complete rather than
  // merely one hop longer than the last one. It is GENERATED by the Supabase CLI,
  // which is exactly why it is worth asserting: nobody reviews it line by line, and
  // it is regenerated by a command any contributor can run.
  //
  // It is not purely types — it carries a runtime `Constants` object of the enum
  // values — so "generated, therefore harmless" is an assumption rather than a
  // fact, and this is what turns it into a checked one.
  it("is pure: no imports of any kind, no network, no clock", () => {
    const violations = findImpurities(
      readModuleSource(new URL("./database.types.ts", import.meta.url).href),
      FORBID_ALL_IMPORTS,
    );

    expect(violations).toEqual([]);
  });
});
